### ISSUE TITLE
Domain cannot be null

### ISSUE THREAD

**Issue by KasonBraley** [Ryan2065/EFPosh#6]
Is it possible to open the context with the DB with a credential that does not have a 'domain'? I continue to receive an error the following error:
`MethodInvocationException: Exception calling "SaveChanges" with "0" argument(s): "Domain cannot be null. (Parameter 'domain')"`

This error is correct, there is no domain specified in my credentials that I am passing in. This is due to using SQL Server Authentication instead of Windows Authentication, or Active Directory authentication. Do you have any advice on this? Is this possible with the current state of the module? 

This error seems to only happen when using the -Credential parameter. When using the -ConnectionString instead, I can get around this error. Using the same credentials that don't have a domain.

**Comment by Ryan2065** [comment]
Credential is specifically for integrated windows authentication. For SQL server authentication, you'll want to put the username / password in the connection string. 

Thanks for the note, I could be clearer with that.
